apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-tour-ci

resources:
## infra resources
- ../infra-ci/

# tasks
- tasks/kustomize-task.yaml
- tasks/maven-task.yaml

# pipelines
- tekton-pipeline.yaml

