apiVersion: v1
kind: Namespace
metadata:
  annotations:
    openshift.io/description: ""
    openshift.io/display-name: "Open Tour - dev"
  labels:
    kubernetes.io/metadata.name: open-tour-dev
  name: open-tour-dev
spec:
  finalizers:
  - kubernetes
