apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: open-tour-ci

resources:
# infra resources
- ns.yaml
- maven-artifact-cache-pvc.yaml
- maven-settings-cm.yaml

# This is an old nexus server which will be installed in book-ci to cache artifacts
# NOTE, you need to change tekton/infra/maven-settings-cm.yaml if you don't want to use
#       THIS nexus instance!
- nexus.yaml
